FROM apache-php-8.2:latest

LABEL   "project"="web-server-apache-php-8.2-dev" \
        "description"="Debian based web server with Apache and PHP 8.2." \
        "vendor.name"="Aeon Digital" \
        "vendor.site"="aeondigital.com.br" \
        "author.name"="Rianna Cantarelli" \
        "author.email"="rianna@aeondigital.com.br"





#
# Define argumentos a serem passados para o momento de build
ARG DEBIAN_FRONTEND=noninteractive

#
# Instalação do XDebug do PHP
RUN buildPacks=" \
        php-xdebug \
    " \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends ${buildPacks}

#
# Instalação dos pacotes que permitem a extração da documentação técnica do
# php, compatível com o 'ReadTheDocs'.
RUN buildPacks=" \
        python3 python3-pip \
    " \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends ${buildPacks} \
    && pip install -U sphinx sphinx_rtd_theme sphinxcontrib-phpdomain recommonmark





#
# Limpa dados temporários do 'apt'
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt

#
# Copia os arquivos de configuração para este build
# [Efetua um 'merge' com os arquivos padrões existentes no container]
# Em seguida, define as permissões de arquivos que necessitam das mesmas
# para funcionar adequadamente
COPY ./configuration-files/dev/etc/. /etc/
RUN [ -f "/etc/mysql/my.cnf" ] && chmod 600 /etc/mysql/my.cnf





#
# Redefine a senha do usuário "root" para permitir que outros usuários
# do mesmo grupo executem ações root sem que seja necessário o prompt
# da mesma.
# Adiciona um grupo de usuário e um usuário para uso dev dos containers.
RUN usermod --password "" root \
    && groupadd dev -g 1000 \
    && useradd dev -u 1000 -g dev -G root --create-home --no-log-init

#
# Define o usuário 'dev' como o ativo para quando o container inicia.
USER dev
